import React from 'react';
import { Metadata } from 'next';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';
import CostCalculator from '@/components/tools/CostCalculator';

export const metadata: Metadata = {
  title: "Pet Cost Calculator: True Cost of Ownership | SoulmatePaw",
  description: "Plan your budget before you adopt. accurate estimates for food, vet bills, and supplies based on breed size and lifestyle.",
};

export default function CostCalculatorPage() {
  return (
    <main className="min-h-screen bg-[#FDFBF7]">
      {/* --- Header Section --- */}
      <section className="bg-white border-b border-gray-100 pt-12 pb-8 px-4 sm:px-6 relative">
        <div className="max-w-4xl mx-auto">
          {/* Back to Home Button */}
          <div className="absolute top-6 left-4 sm:left-6">
            <Link 
              href="/" 
              className="inline-flex items-center gap-2 text-stone-400 hover:text-stone-600 transition-colors font-medium text-sm group"
            >
              <ArrowLeft size={16} className="group-hover:-translate-x-1 transition-transform" /> 
              Back to Home
            </Link>
          </div>

          <div className="text-center space-y-4 pt-6">
            <div className="inline-flex items-center justify-center p-2 bg-[#8DA399]/10 rounded-full mb-2">
              <span className="text-[#8DA399] font-bold text-xs uppercase tracking-widest px-2">
                Financial Planning Tool
              </span>
            </div>
            <h1 className="text-3xl sm:text-4xl font-extrabold text-gray-900 tracking-tight">
              True Cost of Ownership Calculator
            </h1>
            <p className="text-lg text-gray-500 max-w-2xl mx-auto leading-relaxed">
              Financial surprises are a leading cause of pet surrender. We want to stop that. 
              Use our AI-powered calculator to estimate the real cost of your future best friend, 
              so you can focus on the love, not the bills.
            </p>
          </div>
        </div>
      </section>

      {/* --- Calculator Section --- */}
      <section className="py-12 px-4 sm:px-6">
        <CostCalculator />
      </section>

      {/* --- Disclaimer Footer --- */}
      <footer className="max-w-4xl mx-auto px-6 pb-12 text-center">
        <div className="border-t border-gray-200 pt-8">
          <p className="text-xs text-gray-400 italic">
            * Disclaimer: All costs are estimates based on 2025 US Market Data generated by AI analysis. 
            Actual costs may vary significantly based on location, specific brand choices, and unforeseen medical needs. 
            This tool is for planning purposes only.
          </p>
        </div>
      </footer>
    </main>
  );
}
